= Improved RAST Simulator and Load Tester Components (PADS 2024)
:toc:
:toc-title: pass:[<h3>Table of Contents</h3>]

**Last change from: 25.05.2024**

**TODO: Accepted for publication at PADS 2024. Add link.**

In our paper, we explain, implement and evaluate improvements to the following components of RAST:

* Predictive Model Creator,
* Simulator,
* Load Tester.

For our evaluation, we use the https://github.com/DescartesResearch/TeaStore[TeaStore benchmarking application].
We created a GitHub fork <<teastore_fork>> and modified some parameters of their logging framework to create consistent logs especially for higher intensity workloads.

Additional experimental results not published in our paper, including the Python scripts we use for similarity calculation and the validation and prediction data acquired in our experiments, can be accessed in our Datalore notebook <<datalore_notebook>>.

== Instructions for Conducting Experiments

To conduct the experiments outlined in this paper, please follow the step-by-step instructions below:

=== System Requirements

* Linux operating system (we tested with Ubuntu 22.04)

Packages to install (use `sudo apt-get install X` where `X` is the name of the following packages):

* git
* docker-compose
* python3.10-venv
* python3.10-dev
* openjdk-11-jre-headless
* screen

=== Workflow

==== Automated

. Navigate to the Automations module:
+
[source,sh]
----
cd <RAST directory>/Automations
----
. Set up TeaStore on your local machine:
+
[source,sh]
----
cd Setup_TeaStore
./setup.sh
----
. Create Training data for the predictive model component:
+
[source,sh]
----
cd Training_Data
./launch_all.sh
----
+
Wait for the script to finish.
+
** Download the log files and create a training database according to the instructions in xref:../TeaStore/ETL.adoc[ETL].
** Follow the instructions in the xref:../../Regression-Analysis_Workload-Characterization/ReadMe.md[README of Regression-Analysis_Workload-Characterization] to create predictive models from this database.
** Copy the resulting models to the Simulator component and use them according to the instructions in the xref:../../Simulators/README.md[README of Simulators].
. Create Prediction data for Similarity Comparison:
+
[source,sh]
----
cd Prediction_Data
.launch_teastore_loadtest.sh
----
+
Follow the instructions printed in the terminal, like downloading the logs from TeaStore between each load test execution.
+
** After the script finishes, you should have downloaded four different log files with the `.dat` file extension. We recommend naming each file according to the load intensity profile that produced it.
** You need to create a database for each log file individually. Follow the instructions in xref:../TeaStore/ETL.adoc[ETL].
** When you are done, you should have four databases, one for each load intensity profile.
. Create Validation data for Similarity Comparison:
+
[source,sh]
----
cd Validation_Data
----
+
** (Optional) Set the model the Simulator should use:
+
open the `launch_all.sh` file and locate the variables `model` and `model_number_in_simulator`.
+
*** If you want Decision Tree Regression, use:
+
[source,sh]
----
model="teastore_model_DT_T-PR_1_3"
model_number_in_simulator=0
----
*** If you want Ridge Regression, use:
+
[source,sh]
----
model="teastore_model_Ridge_T_PR_1_3"
model_number_in_simulator=1
----
+
** (Optional) Set the maximum number of correction loop iterations:
+
open the `launch_all.sh` file and locate the variable `corr_max_value`.
+
[source,sh]
----
corr_max_value=0
----
or
+
[source,sh]
----
corr_max_value=1
----
** Launch all load tests:
+
[source,sh]
----
./launch_all.sh
----
+
After the script finishes, the resulting log files are located in the Simulators project. The folder is named after the predictive model that the simulator used and has an additional subfolder for the value of `corr_max`.

==== Manual

==== Preparations

* Set up TeaStore according to the https://github.com/jtpgames/RAST/blob/main/docs/TeaStore/Deployment.adoc#setup-teastore[instructions].
* Clone this repository. Make sure to pull all git submodules as well:
+
[source,sh]
----
git clone https://github.com/jtpgames/RAST.git
cd RAST
./pull_all_submodules.sh
----

==== Instructions

. Open your terminal and use a terminal multiplexer such as tmux to create four sessions. We will refer to these sessions by numbers:
    * Session (1): This session will be used to start the TeaStore or the Simulator. Navigate to the respective folder within the cloned repositories.
    * Session (2): This session will be used to start the Load Test. Navigate to the `locust_scripts` folder.
    * Session (3): This session will be used to make code changes to the `offical_teastore_locustfile.py` file, allowing you to modify the load intensity profile. 
      Navigate to the `locust_scripts/locust` folder and open the file using a text editor of your choice (e.g., Vim or Emacs).
    * Session (4): This session will be used to make code changes to the `teastore.kt` file, enabling you to modify the predictive model. 
      Navigate to the Simulators folder and open the file.
. In Session (1), start the TeaStore or the Simulator based on the measurements you wish to acquire.
   For the purpose of this explanation, we will focus on starting the Simulator. 
   Navigate to your local Simulator folder and execute the command `./gradlew run`. 
   If successful, you will see the following line printed on the console: `INFO ktor.application - Responding at http://0.0.0.0:8081`. 
   To terminate the Simulator, press `Ctrl + C`.
. In Session (2):
..  (Recommended):
...     Create a python virtual environment in a directory called `venv`, e.g., `python3 -m venv venv`
...     Run the command `source activate_venv.sh` to activate the Python virtual environment (venv).
...     Run `pip install -r requirements.txt`
..  Execute `./start_teastore_loadtest.sh` to initiate the load test.
    This repository uses a low load intensity by default.
    The load test will automatically conclude after approximately two minutes.
..  Clean the folder by executing `./delete_results.sh`.
. In Session (4), you can now examine the `teastore_simulation.log` file.
  This file contains simulated processing times generated by the predictive model, among other relevant information.
. To modify the load intensity profile,
  navigate to Session (3) and locate the `StagesShape` class within the `offical_teastore_locustfile.py` file.
  Look for the line `load_intensity_profile: LoadIntensityProfile = LoadIntensityProfile.LOW`.
  Set `load_intensity_profile` to your desired value.
. To modify the predictive model,
  navigate to Session (4) and follow the instructions in the README.md file within the Simulators repository.

=== Prediction data
The prediction data as described in the paper was acquired by running a load test against the simulator with each load intensity profile. In between each load test, we copied the resulting teastore_simulation.log file and renamed it accordingly. After acquiring a log file for each load intensity profile, we used our `ResultComparer` found in our Datalore notebook <<datalore_notebook>>. We recommend to take a look at our datalore notebook or the snapshot archive in the Artefact Submission folder to see the recommended naming and structure.

=== Validation data
The validation data is available in our Datalore notebook <<datalore_notebook>>.
Acquiring the validation data from TeaStore is a more complex process involving downloading kieker logs, transforming them and storing into an SQLite database.
The instructions https://github.com/jtpgames/RAST/blob/main/docs/TeaStore/ETL.adoc[here] explain this process.
The validation data is acquired in a similar fashion as the prediction data, i.e., running a load test, creating a database and repeating for each load intensity profile. Again, we recommend to take a look at our datalore notebook or the snapshot archive to see the structure.

== Artefact Submission Inventory

* Datalore notebook(https://datalore.jetbrains.com/notebook/6K6VkECuLMtN5t5nSYg6WK/TVGp1egwDQlwI19astdVlM): Includes instructions, our measurements and the Python code we use for similarity calculation. To access the datalore notebook (similar to a Jupyter notebook) creation of a free account is required.
* RAST_TeaStore_Simulation_Similarity.zip: Exported Datalore notebook snapshot 21.05.2024. The folder `TeaStoreResultComparisonData` includes both the Validation Data and Prediction Data we used in our paper (the datalore notebook above contains a greater set of Prediction Data for models we did not mention in our paper).
* similarity_scores.csv: File created from the ResultComparer Python script found in our Datalore notebook.
* similarity_scores.ods: File created from the similarity_scores.csv file using LibreOffice. Includes all formulaes to assess the experimental results as well as the figures found in the paper. Also includes results and figures not found in the paper.
* Figures: Includes all figures generated using the similarity_scores.ods file.

[bibliography]
== References

* [[[teastore_fork]]](https://github.com/jtpgames/TeaStore)
* [[[simulator_repo]]](https://github.com/jtpgames/Simulators)
* [[[datalore_notebook]]](https://datalore.jetbrains.com/notebook/6K6VkECuLMtN5t5nSYg6WK/TVGp1egwDQlwI19astdVlM)

