#cloud-config

packages:
  - docker.io
  - docker-compose

# create the docker group
groups:
  - docker

# Add default auto created user to docker group
system_info:
  default_user:
    groups: [docker]
